# Generated by Django 4.1.1 on 2022-11-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_division', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subdivision', models.CharField(max_length=25)),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.divisions')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('url_photo', models.URLField(max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('data_entry', models.DateTimeField(auto_now_add=True)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.roles')),
                ('id_subdivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subdivisions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
