# Generated by Django 4.1.3 on 2022-11-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employees_id_subdivision_employeessubdivision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeessubdivision',
            old_name='id_subdivison',
            new_name='id_subdivision',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='id_role',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
