# Generated by Django 4.1.1 on 2022-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roles_employees_id_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='url_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
