# Generated by Django 4.1.3 on 2022-11-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employees_url_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.roles'),
        ),
        migrations.AlterField(
            model_name='employeessubdivision',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees'),
        ),
        migrations.AlterField(
            model_name='employeessubdivision',
            name='id_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subdivisions'),
        ),
        migrations.AlterField(
            model_name='subdivisions',
            name='id_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.divisions'),
        ),
    ]
